### PR TITLE
fix decorate grob vp widths for titles and footers when right margin is present

### PR DESCRIPTION
**Pull request by Melkiades**
#1240

### CODE REVIEW

**Comment by Melkiades** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Melkiades** [comment]
Can someone please help me review this? @ayogasekaram @edelarua Thanks!!

**Review by edelarua — APPROVED** [review]
Lgtm! Thanks Davide!!

**Comment by pawelru** [comment]
Hey Davide. I tried with the example from the issue but I still can't make it work properly. `width_titles = grid::unit(1, "npc")` should indicate full width without margins but apparently it's not like that...
image


Tested in RStudio for now. For some reason I struggle to test in VSCode but I will look into this next.

**Comment by pawelru** [comment]
On VSCode it's ok... Let me dig more into this:
image

**Comment by Melkiades** [comment]
@pawelru rstudio does not work superwell with viewport as far as I could see. Everything works for base R on my machine. Have not tried VS but my output in rstudio is identical to vs

**Comment by pawelru** [comment]
You are right. Base R should be the main testing environment. Tested it there and it's good. Also tested your feature branch versus the main and I can notice that the issue is fixed now. I think it's good to go.
One question though. Is this already covered by any test? I can see edits in one test but it's about margins - not the width of tittle and/or footnote. If not - let's add a new one.

**Comment by Melkiades** [comment]
> You are right. Base R should be the main testing environment. Tested it there and it's good. Also tested your feature branch versus the main and I can notice that the issue is fixed now. I think it's good to go. One question though. Is this already covered by any test? I can see edits in one test but it's about margins - not the width of tittle and/or footnote. If not - let's add a new one.

It is a valid point; I could not think of a proper test for it. I can use the width of the viewport as a test. It is what needs to be respected for the wrapping at the end. 

Btw the wrapping core is not keeping spaces and manual \n as far as I can see. We might want to use the one I wrote for {formatters} that keeps those. What do you think?

**Comment by pawelru** [comment]
> Btw the wrapping core is not keeping spaces and manual \n as far as I can see. We might want to use the one I wrote for {formatters} that keeps those. What do you think?

This I don't know to be honest. I'm afraid that I'm not that deep in this to make a statement. 

I'm going to approve as I can see that the issue had been resolved. Please make a call about the test. If it can't be done then I guess we need to live with that.

**Review by pawelru — APPROVED** [review]

**Comment by Melkiades** [comment]
> > Btw the wrapping core is not keeping spaces and manual \n as far as I can see. We might want to use the one I wrote for {formatters} that keeps those. What do you think?
> 
> This I don't know to be honest. I'm afraid that I'm not that deep in this to make a statement.
> 
> I'm going to approve as I can see that the issue had been resolved. Please make a call about the test. If it can't be done then I guess we need to live with that.

I added and closed an issue to track down my research. Testing for this issue can be a bit difficult considering the inconsistencies between different viewport page sizes' conversions

**Pull request merged**
