### PR TITLE
759 document formats@main

### LINKED ISSUE #759: Create documentation/vignette for tern formats
- format_fraction
 - format_count_fraction
 - format_fraction_fixed_dp
 - format_count_fraction_fixed_dp
 - format_xx
 - format_threshold
 - format_extrme_values
 - format_extrme_values_ci

### PR DESCRIPTION
**Pull request by Nolan-Steed**
Fixes #759

### CODE REVIEW

**Comment by edelarua** [comment]
Hi @Nolan-Steed, I made a bunch of updates to your vignette (grammar, added more examples, etc.) - feel free to re-review the vignette and revert any changes/let me know if you have any questions!

**Review by Nolan-Steed — COMMENTED** [review]
Thanks @edelarua for all of your help with this. Your additions look great!

**Review by edelarua — APPROVED** [review]
@Nolan-Steed looks good to me! I think we've covered the basics, but if we think of anything else to add that can be done later in another PR.

**Comment by shajoezhu** [comment]
FANTASTIC! Thank you so much guys! @Nolan-Steed @edelarua

**Pull request merged**
