### PR TITLE
Fixing sorting in `count_occurence_by_grade()` tests

### LINKED ISSUE #793: Small fix to sorting in test

### PR DESCRIPTION
**Pull request by Melkiades**
Fixes #793

### CODE REVIEW

**Comment by Nolan-Steed** [comment]
Hey @Melkiades I was just looking at the last example with the result dataset being generated on line 430. The rtable outputs a value of 5 for `Grade 1-2`, when looking at the `df` should it not be 6 patients?
image
image

**Comment by Melkiades** [comment]
@Nolan-Steed this is something related to how the function works and not the test itself imo. I will open a dedicated issue from your comment.

**Review by Nolan-Steed — APPROVED** [review]
lgtm!

**Review by Nolan-Steed — COMMENTED** [review]
lgtm!

**Pull request merged**
