### PR TITLE
add faceting variable to g_lineplot. add code to maintain factor levels.

### LINKED ISSUE #1212: [Feature Request]: Add facet + cohort legend strata order in mean plot
### Feature description

Dear NEST,

For a project, we needed to generate a mean plot by Nominal dose (group), but facet by COUNTRY. There was no way of adding a facet to the plot aftewards as the data in the plot is the summarized data with the mean and sd, and the column COUNTRY is lost. We had to manually modify the function so that a second grouping column is kept:

image

These are the code we added to **g_lineplot**:
```r
`#'   * `facetvar` (`character`)\cr name of grouping variable, i.e. treatment arm. Can be `NA` to indicate lack of groups.



  if (is.na(variables["facetvar"])) {
    facetvar <- NULL # NULL if facetvar == NA or it is not in variables
  } else {
    facetvar <- variables[["facetvar"]]
  }




  ####################################### |
  # ---- Compute required statistics ----
  ####################################### |
  if (!is.null(facetvar) & !is.null(strata)) {
    df_grp <- tidyr::expand(df, .data[[facetvar]], .data[[strata]], .data[[x]]) # expand based on levels of factors
  } else  if (!is.null(strata)) {
    df_grp <- tidyr::expand(df, NULL, .data[[strata]], .data[[x]]) # expand based on levels of factors
  } else {
    df_grp <- tidyr::expand(df, NULL, NULL, .data[[x]])
  }
  df_grp <- df_grp %>%
    dplyr::full_join(y = df[, c(facetvar, strata, x, y)], by = c(facetvar, strata, x), multiple = "all") %>%
    dplyr::group_by_at(c(facetvar, strata, x))



#' @export
control_lineplot_vars <- function(x = "AVISIT", y = "AVAL", strata = "ARM", paramcd = "PARAMCD", y_unit = "AVALU",
                                  cohort_id = "USUBJID", facetvar=NA) {
  checkmate::assert_string(x)
  checkmate::assert_string(y)
  checkmate::assert_string(strata, na.ok = TRUE)
  checkmate::assert_string(cohort_id, na.ok = TRUE)
  checkmate::assert_string(paramcd, na.ok = TRUE)
  checkmate::assert_string(y_unit, na.ok = TRUE)
  checkmate::assert_string(facetvar, na.ok = TRUE)
  
  variables <- c(x = x, y = y, strata = strata, paramcd = paramcd, y_unit = y_unit, cohort_id = cohort_id, facetvar=facetvar)
  return(variables)
}


```

And then with the parameter facetvar in the plot, we could produce our plot.

Would it be possible to code something similar to allow us to produce facets on this plot? please

also the legend was incorrect when using strata:
image
Could you check this?
issue raised a month ago:
https://insightsengineering.github.io/tlg-catalog/stable/graphs/pharmacokinetic/pkcg03.html

Best regards
Valentin

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

### PR DESCRIPTION
**Pull request by ayogasekaram**
closes #1212

### CODE REVIEW

**Comment by edelarua** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by edelarua — CHANGES_REQUESTED** [review]
Hi @ayogasekaram,

Thanks for working on this! I generated the updated test snapshots so we can compare the results. It looks pretty good so far, just a few questions from me: 
1. I'm not sure if this is a problem, but I think something you changed affected the y limits (which caused a slight change to 2 of the snapshots). Was this intentional?
2. Now that there is an option to facet, plots could potentially be much more squished together horizontally (which you can see in the new test snapshot). Do you think we should also add a parameter to rotate the x-axis labels for in these cases?

**Comment by ayogasekaram** [comment]
I have read the CLA Document and I hereby sign the CLA.

**Review by edelarua — APPROVED** [review]
Lgtm!

**Comment by legrasv** [comment]
Approved

**Pull request merged**
