### PR TITLE
Fix bug in `decorate_grob`

### LINKED ISSUE #940: [Bug]: `decorate_grob` does not decorate output from `g_km` correctly
### What happened?

```{r}
library(tern)
df <- tern_ex_adtte %>%
  filter(PARAMCD == "OS") %>%
  mutate(is_event = CNSR == 0)
variables <- list(tte = "AVAL", is_event = "is_event", arm = "ARMCD")
res <- g_km(df = df, variables = variables)

res2 <- decorate_grob(
  res,
  title = "this is a test",
  footnote = "this is footnote"
)

png('aa.png', height = 8, width = 6, unit = 'in', res = 72)
grid::grid.draw(res2)
dev.off()
```

image

### sessionInfo()

```R
R version 4.2.2 Patched (2022-11-10 r83330)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.5 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

other attached packages:
[1] tern_0.8.2       rtables_0.6.1    magrittr_2.0.3   formatters_0.5.0

loaded via a namespace (and not attached):
 [1] pillar_1.9.0     compiler_4.2.2   tools_4.2.2      digest_0.6.31   
 [5] lattice_0.20-45  jsonlite_1.8.4   lifecycle_1.0.3  tibble_3.2.1    
 [9] gtable_0.3.3     checkmate_2.2.0  pkgconfig_2.0.3  rlang_1.1.1     
[13] Matrix_1.5-3     cli_3.6.1        fastmap_1.1.1    dplyr_1.1.2     
[17] generics_0.1.3   vctrs_0.6.2      grid_4.2.2       tidyselect_1.2.0
[21] glue_1.6.2       R6_2.5.1         fansi_1.0.4      Rdpack_2.4      
[25] survival_3.5-3   ggplot2_3.4.2    purrr_1.0.1      tidyr_1.3.0     
[29] backports_1.4.1  scales_1.2.1     htmltools_0.5.5  rbibutils_2.2.13
[33] splines_4.2.2    colorspace_2.1-0 renv_0.16.0      utf8_1.2.3      
[37] munsell_0.5.0    broom_1.0.4
```

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

### PR DESCRIPTION
**Pull request by edelarua**
Closes #940

### CODE REVIEW

**Comment by edelarua** [comment]
New output image generate from code originally posted in issue (see [output before bug fix](https://github.com/insightsengineering/tern/issues/940#issue-1730755761)):

aa

**Review by Melkiades — COMMENTED** [review]
Do you think we can test the output in any way?

**Comment by edelarua** [comment]
> Do you think we can test the output in any way?

Other than testing the helper function `split_string` which is already done (we could add more tests of that function if needed), I don't know how we would be able to test the output since it is always an image.

**Review by Melkiades — APPROVED** [review]
I tested both issues and seem to be resolved. Great job! 

btw I was wondering if there is a way to make these legends scale:
Screenshot 2023-06-09 140451

**Pull request merged**
