### PR TITLE
Skip plot snapshot testing

### LINKED ISSUE #1193: skip plot snap testing

### PR DESCRIPTION
**Pull request by edelarua**
# Pull Request

Fixes #1193

### CODE REVIEW

**Comment by edelarua** [comment]
Hi @Melkiades,

I think you recently updated `as_result_df` which is why there's an example now failing. Specifically coming from [this line](https://github.com/insightsengineering/tern/blob/f54ed6fcd772f7579d5355e707f2227407f4dd36/R/g_forest.R#L243) when running [this example](https://github.com/insightsengineering/tern/blob/f54ed6fcd772f7579d5355e707f2227407f4dd36/R/response_biomarkers_subgroups.R#L64).

 Any ideas for a quick fix?

**Comment by shajoezhu** [comment]
> Hi @Melkiades,
> 
> I think you recently updated `as_result_df` which is why there's an example now failing. Specifically coming from [this line](https://github.com/insightsengineering/tern/blob/f54ed6fcd772f7579d5355e707f2227407f4dd36/R/g_forest.R#L243) when running [this example](https://github.com/insightsengineering/tern/blob/f54ed6fcd772f7579d5355e707f2227407f4dd36/R/response_biomarkers_subgroups.R#L64).
> 
> Any ideas for a quick fix?

this issue is also raised in https://github.com/insightsengineering/statistical-engineering/issues/68#issuecomment-1956706307

@Melkiades

**Comment by Melkiades** [comment]
> Hi @Melkiades,
> 
> I think you recently updated `as_result_df` which is why there's an example now failing. Specifically coming from [this line](https://github.com/insightsengineering/tern/blob/f54ed6fcd772f7579d5355e707f2227407f4dd36/R/g_forest.R#L243) when running [this example](https://github.com/insightsengineering/tern/blob/f54ed6fcd772f7579d5355e707f2227407f4dd36/R/response_biomarkers_subgroups.R#L64).
> 
> Any ideas for a quick fix?

I am working on it!

**Review by shajoezhu — APPROVED** [review]
lgtm! thanks @edelarua

**Pull request merged**
