### PR TITLE
Vertically align plot with table in `g_lineplot`

### LINKED ISSUE #1152: [Feature Request]: Align table and plot in g_lineplot
### Feature description

Currently, the table is misaligned vertically with the figure. The table entries are slightly to the right of the axis breaks on the figure at first but eventually resolve.

```
library(nestcolor)

adsl <- tern_ex_adsl
adlb <- tern_ex_adlb %>% dplyr::filter(ANL01FL == "Y", PARAMCD == "ALT", AVISIT != "SCREENING")
adlb$AVISIT <- droplevels(adlb$AVISIT)
adlb <- dplyr::mutate(adlb, AVISIT = forcats::fct_reorder(AVISIT, AVISITN, min))
adlb_f <- dplyr::filter(adlb, ARMCD != "ARM A" | AVISIT == "BASELINE")
g_lineplot(adlb_f, table = c("n", "mean"))
```

image

I believe this can be easily resolved by adding the option `align = 'v'` to https://github.com/insightsengineering/tern/blob/93e729c1e83a30b5f0163eaf6887793f39ec54d7/R/g_lineplot.R#L409

i.e., `cowplot::plot_grid(p, tbl, ncol = 1)`:

image

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

### PR DESCRIPTION
**Pull request by edelarua**
# Pull Request

Fixes #1152

### CODE REVIEW

**Review by ayogasekaram — APPROVED** [review]
thanks @edelarua

**Comment by shajoezhu** [comment]
Hi @edelarua , I was wondering if we need to update tmc downstream, or if this happens automatically

**Comment by edelarua** [comment]
> Hi @edelarua , I was wondering if we need to update tmc downstream, or if this happens automatically

@shajoezhu it will update automatically in tmc - no action needed!

**Comment by shajoezhu** [comment]
Brilliant! Thanks Em

**Pull request merged**
