### PR TITLE
Refactor `g_forest`

### PR DESCRIPTION
**Pull request by edelarua**
# Pull Request

Part of #1109

`g_forest` creates a `ggplot` object instead of a `grob` object.

### CODE REVIEW

**Review by shajoezhu — APPROVED** [review]
looks really good! Thanks @edelarua

**Comment by shajoezhu** [comment]
hi @edelarua , can you introduce this changes in tern.gee and tern.mmrm as well please. thanks!

**Comment by edelarua** [comment]
> hi @edelarua , can you introduce this changes in tern.gee and tern.mmrm as well please. thanks!

Hi @shajoezhu,
`tern.gee` doesn't use `g_forest` anywhere currently. I checked `tern.mmrm` and no changes are needed, we'll just have to update the tern version dependency at some point to use the new version. I will check if `chevron` needs updates tomorrow!

**Comment by shajoezhu** [comment]
Hi @edelarua , it was requested before, but held it because i was wanted to change the gforest implmentation, and you did it! :)

**Comment by shajoezhu** [comment]
Downstream, we will need to update scda.test and tlg.c as well. Thanks!

**Pull request merged**
